from enum import Enum


class Pf2eAreaType(Enum):
    burst = "burst"
    cone = "cone"
    cube = "cube"
    cylinder = "cylinder"
    emanation = "emanation"
    line = "line"
    square = "square"


class Pf2eSaveType(Enum):
    reflex = "reflex"
    will = "will"
    fortitude = "fortitude"

    reflex_dc = "reflex-dc"
    will_dc = "will-dc"
    fortitude_dc = "fortitude-dc"

    ac = "ac"


class Pf2eRarity(Enum):
    uncommon = "uncommon"
    common = "common"
    rare = "rare"
    unique = "unique"


class Pf2eTradition(Enum):
    arcane = "arcane"
    primal = "primal"
    divine = "divine"
    occult = "occult"


class Pf2eTraits(Enum):
    acid = "acid"
    air = "air"
    animist = "animist"
    attack = "attack"
    auditory = "auditory"
    aura = "aura"
    bard = "bard"
    beast = "beast"
    cantrip = "cantrip"
    champion = "champion"
    chaotic = "chaotic"
    cleric = "cleric"
    cold = "cold"
    composition = "composition"
    concentrate = "concentrate"
    conjuration = "conjuration"
    consecration = "consecration"
    contingency = "contingency"
    curse = "curse"
    custom = "custom"
    darkness = "darkness"
    death = "death"
    detection = "detection"
    disease = "disease"
    divination = "divination"
    dream = "dream"
    druid = "druid"
    earth = "earth"
    eidolon = "eidolon"
    electricity = "electricity"
    emotion = "emotion"
    enchantment = "enchantment"
    evil = "evil"
    evocation = "evocation"
    exploration = "exploration"
    extradimensional = "extradimensional"
    fear = "fear"
    fire = "fire"
    focus = "focus"
    force = "force"
    fortune = "fortune"
    fungus = "fungus"
    good = "good"
    healing = "healing"
    hex = "hex"
    holy = "holy"
    illusion = "illusion"
    incapacitation = "incapacitation"
    incarnate = "incarnate"
    incorporeal = "incorporeal"
    lawful = "lawful"
    light = "light"
    linguistic = "linguistic"
    magus = "magus"
    manipulate = "manipulate"
    mental = "mental"
    metal = "metal"
    misfortune = "misfortune"
    monk = "monk"
    morph = "morph"
    move = "move"
    mythic = "mythic"
    necromancy = "necromancy"
    nonlethal = "nonlethal"
    olfactory = "olfactory"
    oracle = "oracle"
    plant = "plant"
    poison = "poison"
    polymorph = "polymorph"
    possession = "possession"
    prediction = "prediction"
    psychic = "psychic"
    ranger = "ranger"
    revelation = "revelation"
    sanctified = "sanctified"
    scrying = "scrying"
    shadow = "shadow"
    sleep = "sleep"
    sonic = "sonic"
    sorcerer = "sorcerer"
    spellshape = "spellshape"
    spirit = "spirit"
    stance = "stance"
    structure = "structure"
    subtle = "subtle"
    summon = "summon"
    summoner = "summoner"
    teleportation = "teleportation"
    transmutation = "transmutation"
    trial = "trial"
    true_name = "true-name"
    unholy = "unholy"
    unique = "unique"
    visual = "visual"
    vitality = "vitality"
    void = "void"
    water = "water"
    witch = "witch"
    wizard = "wizard"
    wood = "wood"
    cursebound = "cursebound"


class Pf2eDamageType(Enum):
    acid = "acid"
    bleed = "bleed"
    bludgeoning = "bludgeoning"
    cold = "cold"
    electricity = "electricity"
    fire = "fire"
    force = "force"
    poison = "poison"
    spirit = "spirit"
    void = "void"
    mental = "mental"
    piercing = "piercing"
    slashing = "slashing"
    sonic = "sonic"
    untyped = "untyped"
    vitality = "vitality"
